config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  resources :accounts
  resources :restaurants
  resources :claims
  resources :dg_imports
  resources :questions do
    resources :options
  end
  devise_for :users, :controllers => { registrations: 'registrations' }

  post 'reset-password', to: 'visitors#generate_new_password_email', as: :reset_password
  get 'contact', to: 'pages#contact'
  post 'contact-submission', to: 'pages#contact_submission'
  get 'about', to: 'pages#about'
  get 'term', to: 'pages#term'

  namespace :api do
    namespace :v1 do
      post 'search', to: 'api#search'
      get  'questions', to: 'api#questions'
      get  'cuisines', to: 'api#cuisines'
      get  'myratings', to: 'api#myratings'
      get  'restaurant-ratings/:id', to: 'api#restaurant_ratings'
      get  'myrestaurants', to: 'api#myrestaurants'
      get  'restaurant/:factual_id', to: 'api#restaurant'
      post 'suggest-restaurant', to: 'api#suggest_restaurant'
      post 'update-restaurant', to: 'api#update_restaurant'
      post 'claim-restaurant', to: 'api#claim_restaurant'
      post 'submit-rating', to: 'api#submit_rating'
      get  'get-client-address', to: 'api#get_client_address'
      post 'submit-food-poisoning-report', to: 'api#submit_food_poisoning_report'
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :options, dependent: :destroy
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:create]
  load_and_authorize_resource except: [:show]
  layout 'admin'
  
  # GET /questions
  def index
  end

  # GET /questions/new
  def new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  def create
    if @question.save
      redirect_to questions_path, notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  # PATCH/PUT /questions/1
  def update
    if @question.update(question_params)
      redirect_to questions_path, notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /questions/1
  def destroy
    @question.destroy
    redirect_to questions_url, notice: 'Question was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.new(question_params)
    end

    # Only allow a trusted parameter "white list" through.
    def question_params
      params.require(:question).permit(:question, :extended, :category, :position)
    end
end

app/views/questions/_form.html.slim
= semantic_form_for @question do |f|
  = f.semantic_errors *f.object.errors.keys
  .row
    .col-md-12
      = f.input :question, input_html: {rows: 3}
      = f.input :extended, label: false
      = f.input :category
      = f.input :position
     
  = f.submit 'Save', class: 'btn btn-primary'
  = link_to 'Back', questions_path, class: 'btn btn-default'

app/views/questions/edit.html.slim
h1 Editing question

= render 'form'

app/views/questions/index.html.slim
h1 Questions

p= link_to 'New question', new_question_path, class: 'btn btn-primary'
table.table
  tr
    th Question
    th Extended
    th Category
    th position
    th
  - @questions.each do |question|
    tr
      td= question.question
      td= question.extended
      td= question.category
      td= question.position
      td
        = link_to 'Options', question_options_path(question), class: 'btn btn-default'
        = link_to 'Edit', edit_question_path(question), class: 'btn btn-primary'
        = link_to 'Destroy', question, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'
br
p= link_to 'New question', new_question_path, class: 'btn btn-primary'

app/views/questions/new.html.slim
h1 New Question

= render 'form'

app/views/questions/show.html.slim
.container
  h1= @question.question
  p
    b Category:
    br
    = @question.category
  p
    b Position:
    br
    = @question.position
  p
    = link_to 'Questions', questions_path, class: 'btn btn-primary'
    = link_to 'Edit', edit_question_path(@question), class: 'btn btn-primary'