config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  resources :accounts
  resources :restaurants
  resources :claims
  resources :dg_imports
  resources :questions do
    resources :options
  end
  devise_for :users, :controllers => { registrations: 'registrations' }

  post 'reset-password', to: 'visitors#generate_new_password_email', as: :reset_password
  get 'contact', to: 'pages#contact'
  post 'contact-submission', to: 'pages#contact_submission'
  get 'about', to: 'pages#about'
  get 'term', to: 'pages#term'

  namespace :api do
    namespace :v1 do
      post 'search', to: 'api#search'
      get  'questions', to: 'api#questions'
      get  'cuisines', to: 'api#cuisines'
      get  'myratings', to: 'api#myratings'
      get  'restaurant-ratings/:id', to: 'api#restaurant_ratings'
      get  'myrestaurants', to: 'api#myrestaurants'
      get  'restaurant/:factual_id', to: 'api#restaurant'
      post 'suggest-restaurant', to: 'api#suggest_restaurant'
      post 'update-restaurant', to: 'api#update_restaurant'
      post 'claim-restaurant', to: 'api#claim_restaurant'
      post 'submit-rating', to: 'api#submit_rating'
      get  'get-client-address', to: 'api#get_client_address'
      post 'submit-food-poisoning-report', to: 'api#submit_food_poisoning_report'
    end
  end
end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :question
  has_many :answers, dependent: :destroy
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_question
  before_action :set_option, only: [:create]
  load_and_authorize_resource except: [:show]
  layout 'admin'
  
  # GET /options
  def index
    @options = @options.where(question_id: @question)
  end

  # GET /options/new
  def new
  end

  # GET /options/1/edit
  def edit
  end

  # POST /options
  def create
    @option.question = @question
    if @option.save
      redirect_to question_options_path, notice: 'Option was successfully created.'
    else
      render :new
    end
  end

  def show
    @option = Option.find(params[:id])
  end

  # PATCH/PUT /options/1
  def update
    if @option.update(option_params)
      redirect_to question_options_path, notice: 'Option was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /options/1
  def destroy
    @option.destroy
    redirect_to question_options_url, notice: 'Option was successfully destroyed.'
  end

  private
    def set_question
      @question = Question.find(params[:question_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_option
      @option = Option.new(option_params)
    end

    # Only allow a trusted parameter "white list" through.
    def option_params
      params.require(:option).permit(:quesiton_id, :title, :deduction, :position)
    end
end

app/views/options/_form.html.slim
= semantic_form_for [@question, @option] do |f|
  = f.semantic_errors *f.object.errors.keys
  .row
    .col-md-12
      = f.input :title, input_html: {rows: 3}
      = f.input :deduction
      = f.input :position
     
  = f.submit 'Save', class: 'btn btn-primary'
  = link_to 'Back', question_options_path(@question), class: 'btn btn-default'

app/views/options/edit.html.slim
h1 Editing option

= render 'form'

app/views/options/index.html.slim
h1= @question.question

p= link_to 'New option', new_question_option_path(@question), class: 'btn btn-primary'
table.table
  tr
    th Title
    th Deduction
    th position
    th
  - @options.each do |option|
    tr
      td= option.title
      td= option.deduction
      td= option.position
      td
        = link_to 'Edit', edit_question_option_path(@question, option), class: 'btn btn-primary'
        = link_to 'Destroy', question_option_path(@question, option), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'
br
p= link_to 'New option', new_question_option_path(@question), class: 'btn btn-primary'

app/views/options/new.html.slim
h1 New Option

= render 'form'