config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  resources :accounts
  resources :restaurants
  resources :claims
  resources :dg_imports
  resources :questions do
    resources :options
  end
  devise_for :users, :controllers => { registrations: 'registrations' }

  post 'reset-password', to: 'visitors#generate_new_password_email', as: :reset_password
  get 'contact', to: 'pages#contact'
  post 'contact-submission', to: 'pages#contact_submission'
  get 'about', to: 'pages#about'
  get 'term', to: 'pages#term'

  namespace :api do
    namespace :v1 do
      post 'search', to: 'api#search'
      get  'questions', to: 'api#questions'
      get  'cuisines', to: 'api#cuisines'
      get  'myratings', to: 'api#myratings'
      get  'restaurant-ratings/:id', to: 'api#restaurant_ratings'
      get  'myrestaurants', to: 'api#myrestaurants'
      get  'restaurant/:factual_id', to: 'api#restaurant'
      post 'suggest-restaurant', to: 'api#suggest_restaurant'
      post 'update-restaurant', to: 'api#update_restaurant'
      post 'claim-restaurant', to: 'api#claim_restaurant'
      post 'submit-rating', to: 'api#submit_rating'
      get  'get-client-address', to: 'api#get_client_address'
      post 'submit-food-poisoning-report', to: 'api#submit_food_poisoning_report'
    end
  end
end

app/models/dg_import.rb
class DgImport < ActiveRecord::Base
  has_many :dg_ratings, :dependent => :destroy

  def type_label
    if self.import_type=='HD'
      'Health Department'
    else
      'Old Rating CSV'
    end
  end
end

app/controllers/dg_imports_controller.rb
class DgImportsController < ApplicationController
  load_and_authorize_resource except: [:show]
  layout 'admin'

  def index
    authorize! :manage, Restaurant
    @csv_files = DgImport.all
  end

  def new
  end

  def create
    uploaded_csv = params[:csv]
    license_id = params[:license_id].to_sym
    title = params[:title].to_sym
    address = params[:address].to_sym
    city = params[:city].to_sym
    state = params[:state].to_sym
    zip = params[:zip].to_sym
    telephone = params[:telephone].to_sym
    dateOfinspection = params[:dateOfinspection].to_sym
    cleanliness_rating = params[:cleanliness_rating].to_sym
    lon = params[:lon].to_sym
    lat = params[:lat].to_sym

    notice = ''
    if uploaded_csv
      add_num = 0
      update_num = 0
      error_num = 0

      import = DgImport.create(file_name: uploaded_csv.original_filename,
                          import_type: 'HD')

      CSV.parse(uploaded_csv.read, :headers => true).each_with_index do |line, i|
        row = line.to_hash.symbolize_keys!
        
        if row[license_id].present? and row[title].present? and row[address].present?
          #res = DgRating.where(license_id: row[license_id]).last
          rating = row[cleanliness_rating].to_i / 20.0
          begin
            phone = ''
            if row[telephone].present?
              phone = row[telephone].gsub /[()\-\s+]/, ''
            end
            lon_val = row[lon].nil? ? 0 : "%0.6f" % row[lon].to_d
            lat_val = row[lat].nil? ? 0 : "%0.6f" % row[lat].to_d
            res = DgRating.new(license_id: row[license_id],
                                restaurant_name: row[title],
                                address: row[address],
                                city: row[city],
                                state: row[state],
                                zip: row[zip],
                                telephone: phone,
                                dateOfDine: row[dateOfinspection],
                                cleanliness_rating: rating,
                                satisfaction_rating: rating,
                                recommendation_rating: rating,
                                lon: lon_val,
                                lat: lat_val,
                                dg_import_id: import.id)

            res.save!
            add_num += 1
          rescue Exception => e
            error_num += 1
          end
        else
          error_num += 1
        end
      end
      notice = "Inserted #{add_num} rows, and had #{error_num} errors"

      import.update_attributes(total: add_num + update_num + error_num,
                              insert_cnt: add_num,
                              update_cnt: update_num,
                              error_cnt: error_num)
    else
      notice = 'csv file is empty'
    end

    redirect_to dg_imports_path, notice: notice
    
  end

  def destroy
    import_csv = DgImport.find(params[:id])
    import_csv.destroy

    redirect_to dg_imports_url, notice: 'Imported file was successfully destroyed.'
  end

end

app/views/dg_imports/index.html.slim
h1 Import Health Department Ratings
p= link_to 'Import', new_dg_import_path(), class: 'btn btn-primary'
table.table
  tr
    th File Name
    th Total
    th Inserted
    th Error
    th Imported Date
    th Import Type
    th
  - @csv_files.each do |csv|
    tr
      td= csv.file_name
      td= csv.total
      td= csv.insert_cnt
      td= csv.error_cnt
      td= csv.created_at
      td= csv.type_label
      td
        = link_to 'Destroy', dg_import_path(csv), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'
br
p= link_to 'Import', new_dg_import_path(), class: 'btn btn-primary'

app/views/dg_imports/new.html.slim
h1 Import Health Department Ratings
hr
= form_tag dg_imports_path, method: 'post', multipart: true, class: 'form-horizontal' do
  div.form-group
    label.col-sm-2 CSV File
    div.col-sm-10
      = file_field_tag 'csv', accept: '.csv'
  div.form-group
    label.col-sm-2 License ID
    div.col-sm-4
      input.form-control type="text" name="license_id" value="License_id"
  div.form-group
    label.col-sm-2 Title
    div.col-sm-4
      input.form-control type="text" name="title" value="title"
  div.form-group
    label.col-sm-2 Address
    div.col-sm-4
      input.form-control type="text" name="address" value="address"
  div.form-group
    label.col-sm-2 City
    div.col-sm-4
      input.form-control type="text" name="city" value="city"
  div.form-group
    label.col-sm-2 State
    div.col-sm-4
      input.form-control type="text" name="state" value="state"
  div.form-group
    label.col-sm-2 Zip
    div.col-sm-4
      input.form-control type="text" name="zip" value="zip"
  div.form-group
    label.col-sm-2 Telephone
    div.col-sm-4
      input.form-control type="text" name="telephone" value="telephone"
  div.form-group
    label.col-sm-2 Date of inspection
    div.col-sm-4
      input.form-control type="text" name="dateOfinspection" value="dateOfInspection"
  div.form-group
    label.col-sm-2 Rating
    div.col-sm-4
      input.form-control type="text" name="cleanliness_rating" value="cleanliness_rating"
  div.form-group
    label.col-sm-2 Lon
    div.col-sm-4
      input.form-control type="text" name="lon" value="lon"
  div.form-group
    label.col-sm-2 Lat
    div.col-sm-4
      input.form-control type="text" name="lat" value="lat"

  div.form-group
    div.col-sm-offset-2.col-sm-10
      button.btn.btn-primary type="submit" Submit