config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  resources :accounts
  resources :restaurants
  resources :claims
  resources :dg_imports
  resources :questions do
    resources :options
  end
  devise_for :users, :controllers => { registrations: 'registrations' }

  post 'reset-password', to: 'visitors#generate_new_password_email', as: :reset_password
  get 'contact', to: 'pages#contact'
  post 'contact-submission', to: 'pages#contact_submission'
  get 'about', to: 'pages#about'
  get 'term', to: 'pages#term'

  namespace :api do
    namespace :v1 do
      post 'search', to: 'api#search'
      get  'questions', to: 'api#questions'
      get  'cuisines', to: 'api#cuisines'
      get  'myratings', to: 'api#myratings'
      get  'restaurant-ratings/:id', to: 'api#restaurant_ratings'
      get  'myrestaurants', to: 'api#myrestaurants'
      get  'restaurant/:factual_id', to: 'api#restaurant'
      post 'suggest-restaurant', to: 'api#suggest_restaurant'
      post 'update-restaurant', to: 'api#update_restaurant'
      post 'claim-restaurant', to: 'api#claim_restaurant'
      post 'submit-rating', to: 'api#submit_rating'
      get  'get-client-address', to: 'api#get_client_address'
      post 'submit-food-poisoning-report', to: 'api#submit_food_poisoning_report'
    end
  end
end

app/views/layouts/_footer.html.slim
.container
  = inline_svg 'icons/down-long-arrow.svg', class: 'svg-down-long-arrow'
  h2 Dine with Confidence. Dine with Us.
  a.btn.btn-default.btn-lg href="/" FIND A RESTAURANT
  ul
    li
      =link_to 'About', about_path
    li
      =link_to 'Contact', contact_path
    li
      a href="" Blog
    li
      a href="" Food Courses
    li
      =link_to 'Privacy', term_path
  div.company-brand
    .logo
    .brand
  p.copyright
    | &copy; Copyright Dining Grades. All Rights Reserved.
    br
    | Website developed by 
    a href="http://www.bkmediagroup.com/" target="bkmediagroup" rel="nofollow" BKMedia Group
.footer-menu
  span.cursor.show-footer-arrow
    | Footer Menu
    = inline_svg 'icons/up-long-arrow.svg', class: 'svg-up-long-arrow'

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top ng-controller="TopNavCtrl"
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, class: 'navbar-brand'
        .logo
        span
          div.brand
          div.italic monitoring food cleanliness & improving food safety
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
li.hide-item.login
  a#login href="javascript:void(0)" ng-click="login()"
    | Login
li.divider.hidden-xs.hide-item.login |
li.hide-item.login
  a#signup href="javascript:void(0)" ng-click="signup()"
    | Sign Up

li.hide-item.logout-admin
  =link_to 'Restaurants', restaurants_path
li.divider.hidden-xs.hide-item.logout-admin |
li.hide-item.logout-admin
  =link_to 'Claims', claims_path
li.divider.hidden-xs.hide-item.logout-admin |
li.hide-item.logout-admin
  =link_to 'Questions', questions_path
li.divider.hidden-xs.hide-item.logout-admin |
li.hide-item.logout
  a href="accounts"
    | My Account
li.divider.hidden-xs.hide-item.logout |
li.hide-item.logout
  a#logout href="javascript:void(0)" ng-click="logout()"
    | Log Out

app/views/layouts/_search_box.html.slim
#search-box ng-controller="SearchCtrl" data-controller="#{controller.controller_name}"
  .container
    dl.dl-horizontal
      dt
        h2
          | Find a Restaurant:
          i.fa.fa-angle-double-down
          i.fa.fa-angle-double-up
      dd
        .col-md-12.col-sm-12.col-xs-12
          .col-md-3.col-sm-3.col-xs-3.col-xxs-12
            div.form-group
              label CITY, STATE OR ZIP
              input#txtSearch.form-control.input-lg type="text" ng-enter="searchRestaurants()" placeholder="" ng-model="search.address"
          .col-md-3.col-sm-3.col-xs-3.col-xxs-12
            div.form-group.dropdown
              label TYPE OF CUISINE
              button.btn.btn-default.btn-lg.btn-block data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                | {{search.cuisinelabel}}
                span.glyphicon.glyphicon-menu-down
              input#txtCuisineType type="hidden" ng-model="search.cuisine"
              ul.dropdown-menu
                li ng-repeat="cuisine in cuisines" ng-click="search.cuisine=cuisine.value;search.cuisinelabel=cuisine.label"
                  a href="#" {{cuisine.label}}
          .col-md-3.col-sm-3.col-xs-3.col-xxs-12
            div.form-group.dropdown
              label GRADE
              button.btn.btn-default.btn-lg.btn-block data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                | {{search.gradelabel}}
                span.glyphicon.glyphicon-menu-down
              input#txtGrade type="hidden" ng-model="search.grade"
              ul.dropdown-menu
                li ng-repeat="grade in grades" ng-click="search.grade=grade.value;search.gradelabel=grade.label"
                  a href="#" {{grade.label}}
          .col-md-3.col-sm-3.col-xs-3.col-xxs-12
            button.btn.btn-default.btn-lg.btn-block#btn-search ng-click="searchRestaurants()"
              | SEARCH
              = inline_svg 'icons/circle-right-arrow.svg', class: 'svg-circle-right-arrow'

app/views/layouts/_sign_in_up.html.slim
div ng-controller="SigninupCtrl"
  #loginModal.modal.signinup-modal.fade
    .modal-dialog
      .modal-content
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true"
          | Close
          span.glyphicon.glyphicon-remove
        .forgot-password ng-click="showForgetPwdModal()"
          | Forgot Password?
        .get-started
          | Don't have an account? 
          span.cusor ng-click="showSignup()" GET STARTED!
        .modal-header
          .company-brand
            .logo
            .brand
        .modal-body
          h2 Login to Your Account
          .hello ng-show="afterLogin=='submit-rating'"
            | Hello! You will need an account to save your rating. 
            a href="#" ng-click="showSignup()"
              u Create an account.
          form
            div.form-group
              label EMAIL ADDRESS
              input type="email" class="form-control input-lg" placeholder="Email Address" ng-model="loginForm.email"
            div.form-group
              label PASSWORD
              input type="password" class="form-control input-lg" placeholder="Password" ng-model="loginForm.password"
            .error ng-show="loginError" {{loginError}}
            button.btn-lg-green.btn-block ng-click="submitLoginForm()"
              | LOGIN

  #signupModal.modal.signinup-modal.fade
    .modal-dialog
      .modal-content
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true"
          | Close
          span.glyphicon.glyphicon-remove
        .login
          | Already have an account? 
          span.cursor ng-click="showLogin()" LOGIN!
        .modal-header
          .company-brand
            .logo
            .brand
        .modal-body
          h2
            | Get Started Absolutely 
            span.green FREE.
          h5 No credit card needed, just good ol' fashioned rating.
          form
            div.row
              .col-md-8
                div.form-group
                  label PROFILE DISPLAY NAME*
                  input type="text" class="form-control input-lg" placeholder="Profile Display Name" ng-model="registrationForm.name"
              .col-md-4
                div.form-group
                  label ZIP CODE*
                  input type="text" class="form-control input-lg" placeholder="Zip Code" ng-model="registrationForm.zipcode"
            div.form-group
              label EMAIL ADDRESS*
              input type="email" class="form-control input-lg" placeholder="Email Address" ng-model="registrationForm.email"
            div.form-group
              label PASSWORD*
              input type="password" class="form-control input-lg" placeholder="Password" ng-model="registrationForm.password"
            div.form-group
              label CONFIRM PASSWORD
              input type="password" class="form-control input-lg" placeholder="Confirm Password" ng-model="registrationForm.password_confirmation"
            .error ng-show="registerErrors" Data does not match. Try again.
            button.btn-lg-green.btn-block ng-click="submitRegistrationForm()"
              | SIGN UP FOR FREE
          h5.terms
            | By clicking "Sign Up For Free" I agree to Dining Grades 
            span
              =link_to 'Terms of Service', term_path
            | .

  #updateModal.modal.signinup-modal.fade
    .modal-dialog
      .modal-content
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true"
          | Close
          span.glyphicon.glyphicon-remove
        .modal-header
          .company-brand
            .logo
            .brand
        .modal-body
          form
            div.row
              .col-md-8.col-sm-8.col-xs-12
                div.form-group
                  label PROFILE DISPLAY NAME*
                  input type="text" class="form-control input-lg" placeholder="Profile Display Name" ng-model="user.name"
              .col-md-4.col-sm-4.col-xs-12
                div.form-group
                  label ZIP CODE*
                  input type="text" class="form-control input-lg" placeholder="Zip Code" ng-model="user.zipcode"
            div.form-group
              label EMAIL ADDRESS*
              input type="email" class="form-control input-lg" placeholder="Email Address" ng-model="user.email"
            .error ng-show="updateErrors" Data does not valid. Try again.
            button.btn-lg-green.btn-block ng-click="updateAccount()"
              | UPDATE ACCOUNT

  #passwordModal.modal.signinup-modal.fade
    .modal-dialog
      .modal-content
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true"
          | Close
          span.glyphicon.glyphicon-remove
        .modal-header
          .company-brand
            .logo
            .brand
        .modal-body
          form
            div.form-group
              label CURRENT PASSWORD*
              input type="password" class="form-control input-lg" placeholder="Current Password" ng-model="tuser.current_password"
            div.form-group
              label PASSWORD*
              input type="password" class="form-control input-lg" placeholder="Password" ng-model="tuser.password"
            div.form-group
              label CONFIRM PASSWORD
              input type="password" class="form-control input-lg" placeholder="Confirm Password" ng-model="tuser.password_confirmation"
            .error ng-show="passwordErrors" {{passwordErrors}}
            button.btn-lg-green.btn-block ng-click="updatePassword()"
              | UPDATE PASSWORD

  #forgetPwdModal.modal.signinup-modal.fade
    .modal-dialog
      .modal-content
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true"
          | Close
          span.glyphicon.glyphicon-remove
        .modal-header
          .company-brand
            .logo
            .brand
        .modal-body
          form
            div.form-group
              label EMAIL ADDRESS*
              input type="email" class="form-control input-lg" placeholder="Email Address" ng-model="resetEmail"
            .error ng-show="resetEmailError" {{resetEmailError}}
            button.btn-lg-green.btn-block ng-click="sendResetPwdEmail()"
              | SEND EMAIL

  #noticeModal.modal.signinup-modal.fade
    .modal-dialog
      .modal-content
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true"
          | Close
          span.glyphicon.glyphicon-remove
        .modal-header
          .company-brand
            .logo
            .brand
        .modal-body
          .notice
            | {{notice}}

app/views/layouts/admin.html.slim
- provide :content do
  == render 'layouts/sign_in_up'
  .container.admin
    == render 'layouts/messages'
    = yield
  
== render template: 'layouts/base'

app/views/layouts/application.html.slim
- provide :content do
  == render 'layouts/search_box'
  == render 'layouts/sign_in_up'
  = yield
  
== render template: 'layouts/base'

app/views/layouts/base.html.slim
doctype html
html[ng-app="dininggradesApp"]
  head
    meta[charset="UTF-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Dininggrades'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Dininggrades'}"
    == stylesheet_link_tag "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"
    == stylesheet_link_tag "http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext"
    == stylesheet_link_tag "application", :media => 'all'
    == javascript_include_tag 'application'
    script src="http://maps.google.com/maps/api/js" 
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]= yield :content
    footer
      == render 'layouts/footer'

app/views/layouts/email.html.slim
doctype html
html[ng-app="dininggradesApp"]
  head
    meta[charset="UTF-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title 'Dininggrades'
  body
    = yield